/**
 * getDeepgramAuraAudio — Returns a buffer of the audio generated by Deepgram Aura
 * Aura is designed for low-latency voice AI.
 */
async function getDeepgramAuraAudio(text, model = "aura-asteria-en") {
  const apiKey = process.env.DEEPGRAM_API_KEY;
  
  if (!apiKey) {
    console.warn("[Deepgram TTS] API Key missing");
    return null;
  }

  try {
    const url = `https://api.deepgram.com/v1/speak?model=${model}&encoding=mulaw&sample_rate=8000`;
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Authorization": `Token ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ text })
    });

    if (!response.ok) {
      const err = await response.text();
      console.error(`[Deepgram TTS ERROR] Status: ${response.status} | Msg: ${err}`);
      return null;
    }

    const audioBuffer = Buffer.from(await response.arrayBuffer());
    return audioBuffer;
  } catch (error) {
    console.error("[Deepgram TTS] Request failed:", error.message);
    return null;
  }
}

module.exports = { getDeepgramAuraAudio };
