// Using global fetch (available in Node 21+)

/**
 * getElevenLabsAudio — Returns a buffer of the audio generated by ElevenLabs
 */
async function getElevenLabsAudio(text) {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  const voiceId = process.env.ELEVENLABS_VOICE_ID || '21m00Tcm4TlvDq8ikWAM'; // Default Joanna-like voice

  if (!apiKey) {
    console.warn("[ElevenLabs] API Key missing, falling back to null");
    return null;
  }

  try {
    const response = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}/stream`, {
      method: 'POST',
      headers: {
        'Accept': 'audio/mpeg',
        'Content-Type': 'application/json',
        'xi-api-key': apiKey
      },
      body: JSON.stringify({
        text: text,
        model_id: 'eleven_turbo_v2_5',
        voice_settings: {
          stability: 0.5,
          similarity_boost: 0.8
        }
      })
    });

    if (!response.ok) {
      const err = await response.text();
      console.error(`[ElevenLabs ERROR] Status: ${response.status} | Msg: ${err}`);
      return null;
    }

    return Buffer.from(await response.arrayBuffer());
  } catch (error) {
    console.error("[ElevenLabs] Request failed:", error.message);
    return null;
  }
}

module.exports = { getElevenLabsAudio };
