const ROLES = {
  SUPERADMIN: "SUPERADMIN",
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  AGENT: "AGENT",
  STAFF: "STAFF",
  DEVELOPER: "DEVELOPER",
  MANAGER: "MANAGER",
  PRODUCT: "PRODUCT"
};

module.exports = { ROLES };